/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dia2programa4;

/**
 *
 * @author Participante
 */
public class Calculadora extends javax.swing.JFrame {
    Double operador1;
    Double operador2;
    String cadena;
    String mensaje;
    
    public void cargar(){
        borrarmensaje();
        try {
            operador1=Double.parseDouble(jToperador1.getText());
            operador2=Double.parseDouble(jToperador2.getText());
        }
        catch (Exception e) {
            jLmensaje.setText("Disculpe! Debe introducir solo numeros.");
        }
    }
    
    public String mostrar(Double resultado){
        cadena=String.valueOf(resultado);
        return cadena;
    }
    
    public void borrarmensaje() {
        jLmensaje.setText("");
    }
    
    public void limpiar(){
        jToperador1.setText("");
        jToperador2.setText("");
        jLresultadooperacion.setText("");
        borrarmensaje();
    }
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLoperador1 = new javax.swing.JLabel();
        jLoperador2 = new javax.swing.JLabel();
        jToperador1 = new javax.swing.JTextField();
        jToperador2 = new javax.swing.JTextField();
        jLresultado = new javax.swing.JLabel();
        jLresultadooperacion = new javax.swing.JLabel();
        jBsuma = new javax.swing.JButton();
        jBresta = new javax.swing.JButton();
        jBmultiplica = new javax.swing.JButton();
        jBdivide = new javax.swing.JButton();
        jLmensaje = new javax.swing.JLabel();
        jBlimpiar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");

        jLoperador1.setText("Operador 1");

        jLoperador2.setText("Operador 2");

        jToperador1.setText("jTextField1");
        jToperador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToperador1ActionPerformed(evt);
            }
        });

        jToperador2.setText("jTextField2");

        jLresultado.setText("Resultado");

        jLresultadooperacion.setText("jLabel3");

        jBsuma.setText("Suma");
        jBsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsumaActionPerformed(evt);
            }
        });

        jBresta.setText("Resta");
        jBresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrestaActionPerformed(evt);
            }
        });

        jBmultiplica.setText("Multiplica");
        jBmultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmultiplicaActionPerformed(evt);
            }
        });

        jBdivide.setText("Divide");
        jBdivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdivideActionPerformed(evt);
            }
        });

        jLmensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLmensaje.setText("jLabel2");

        jBlimpiar.setText("Limpiar");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jBsalir.setForeground(new java.awt.Color(204, 0, 0));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLoperador2)
                                    .addComponent(jLresultado))
                                .addGap(18, 18, 18)
                                .addComponent(jLresultadooperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jToperador2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLoperador1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToperador1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBresta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBmultiplica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBdivide, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoperador1)
                    .addComponent(jToperador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoperador2)
                    .addComponent(jToperador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLresultado)
                    .addComponent(jLresultadooperacion))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsuma)
                    .addComponent(jBresta)
                    .addComponent(jBmultiplica)
                    .addComponent(jBdivide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlimpiar)
                    .addComponent(jBsalir))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToperador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToperador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToperador1ActionPerformed

    private void jBrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrestaActionPerformed
        // TODO add your handling code here:
        cargar();
        Double resultado=operador1-operador2;
        jLresultadooperacion.setText(mostrar(resultado));
    }//GEN-LAST:event_jBrestaActionPerformed

    private void jBdivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdivideActionPerformed
        // TODO add your handling code here:
        cargar();
        Double resultado=operador1/operador2;
        jLresultadooperacion.setText(mostrar(resultado));
    }//GEN-LAST:event_jBdivideActionPerformed

    private void jBsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsumaActionPerformed
        // TODO add your handling code here:
        cargar();
        Double resultado=operador1+operador2;
        jLresultadooperacion.setText(mostrar(resultado));
        
    }//GEN-LAST:event_jBsumaActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBmultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmultiplicaActionPerformed
        // TODO add your handling code here:
        cargar();
        Double resultado=operador1*operador2;
        jLresultadooperacion.setText(mostrar(resultado));
    }//GEN-LAST:event_jBmultiplicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdivide;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jBmultiplica;
    private javax.swing.JButton jBresta;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jBsuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLmensaje;
    private javax.swing.JLabel jLoperador1;
    private javax.swing.JLabel jLoperador2;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JLabel jLresultadooperacion;
    private javax.swing.JTextField jToperador1;
    private javax.swing.JTextField jToperador2;
    // End of variables declaration//GEN-END:variables
}
