/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dia3programafinal;

import java.sql.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Instructor
 */
public class TablaOcurrencia extends javax.swing.JFrame {
    ArrayList<Ocurrencia> lo=new ArrayList<Ocurrencia>();
    /**
     * Creates new form TablaOcurrencia
     */
    public TablaOcurrencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLevento = new javax.swing.JLabel();
        jLfalla = new javax.swing.JLabel();
        jLfechaevento = new javax.swing.JLabel();
        jTcodfalla = new javax.swing.JTextField();
        jClistaeventos = new javax.swing.JComboBox<>();
        jTfechaevento = new javax.swing.JTextField();
        jBvolver = new javax.swing.JButton();
        jLfechareparacion = new javax.swing.JLabel();
        jTfechareparacion = new javax.swing.JTextField();
        jLstatus = new javax.swing.JLabel();
        jTestatusactual = new javax.swing.JTextField();
        jLtrabajador = new javax.swing.JLabel();
        jTcodtrabajador = new javax.swing.JTextField();
        jLnombrefalla = new javax.swing.JLabel();
        jLnombretrabajador = new javax.swing.JLabel();
        jBguardar = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jCelementosestatus = new javax.swing.JComboBox<>();
        jLlistaestatus = new javax.swing.JLabel();
        jBcambioestatus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBconsultar = new javax.swing.JButton();
        jBbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tabla de Ocurrencia");

        jLevento.setText("Codigo");

        jLfalla.setText("Falla");

        jLfechaevento.setText("Fecha Evento");

        jClistaeventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evento" }));

        jTfechaevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfechaeventoActionPerformed(evt);
            }
        });

        jBvolver.setText("Regresar");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        jLfechareparacion.setText("Fecha Reparacion");

        jLstatus.setText("Estatus");

        jTestatusactual.setEditable(false);

        jLtrabajador.setText("Trabajador");

        jTcodtrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcodtrabajadorActionPerformed(evt);
            }
        });

        jLnombrefalla.setText("Descripcion");

        jLnombretrabajador.setText("Nombre y Apellido");

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBmodificar.setText("Modificar");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });

        jBborrar.setText("Borrar");
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        jCelementosestatus.setMaximumRowCount(3);
        jCelementosestatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus", "Reparado", "En Proceso", "Otra Cola" }));
        jCelementosestatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCelementosestatusItemStateChanged(evt);
            }
        });
        jCelementosestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCelementosestatusActionPerformed(evt);
            }
        });

        jLlistaestatus.setText("Nuevo Estatus");

        jBcambioestatus.setForeground(new java.awt.Color(51, 102, 0));
        jBcambioestatus.setText("Ok");
        jBcambioestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcambioestatusActionPerformed(evt);
            }
        });

        jBconsultar.setText("Actualizar");
        jBconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarActionPerformed(evt);
            }
        });

        jBbuscar.setForeground(new java.awt.Color(51, 102, 0));
        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLtrabajador)
                                    .addComponent(jLevento)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLfechaevento)
                                            .addComponent(jLfechareparacion)
                                            .addComponent(jLstatus))
                                        .addComponent(jLlistaestatus))
                                    .addComponent(jLfalla))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTcodfalla, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLnombrefalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTfechaevento, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCelementosestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBcambioestatus))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTestatusactual, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTfechareparacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jClistaeventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBbuscar)))
                                        .addGap(0, 92, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTcodtrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLnombretrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBvolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBconsultar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBvolver)
                    .addComponent(jLabel1)
                    .addComponent(jBconsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLevento)
                    .addComponent(jClistaeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTcodfalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnombrefalla)
                    .addComponent(jLfalla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLnombretrabajador)
                    .addComponent(jTcodtrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtrabajador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLfechaevento)
                    .addComponent(jTfechaevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLfechareparacion)
                    .addComponent(jTfechareparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLstatus)
                    .addComponent(jTestatusactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCelementosestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLlistaestatus)
                    .addComponent(jBcambioestatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBmodificar)
                    .addComponent(jBborrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal mp=new MenuPrincipal();
        dispose();
        mp.show();
    }//GEN-LAST:event_jBvolverActionPerformed

    private void jCelementosestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCelementosestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCelementosestatusActionPerformed

    private void jCelementosestatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCelementosestatusItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCelementosestatusItemStateChanged

    private void jBcambioestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcambioestatusActionPerformed
        // TODO add your handling code here:
        int estatus=jCelementosestatus.getSelectedIndex();
        if(estatus!=0){
            jTestatusactual.setText((String) jCelementosestatus.getSelectedItem());
        }
    }//GEN-LAST:event_jBcambioestatusActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conexion=DriverManager.getConnection("jdbc:mysql://localhost/eventos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDateTimeCode=false&serverTimezone=UTC","root","");
            String sql="INSERT INTO ocurrencia (cod_falla,fecha_ocu,fecha_rep,cod_trabajador,estatus) VALUES (?,?,?,?,?)";
            PreparedStatement ps=null;
            ps=conexion.prepareStatement(sql);
            /*
            ps.setInt(1,1);
            ps.setInt(2,1);
            ps.setString(3,"2018-10-01");
            ps.setString(4,"2018-10-03");
            ps.setInt(5,1);
            ps.setString(6,"Re");
            */
            ps.setInt(1, Integer.parseInt(jTcodfalla.getText()));
            ps.setString(2,jTfechaevento.getText());
            ps.setString(3,jTfechareparacion.getText());
            ps.setInt(4, Integer.parseInt(jTcodtrabajador.getText()));
            ps.setString(5,jTestatusactual.getText());
            ps.executeUpdate();
            
        }   
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TablaOcurrencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jTcodtrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcodtrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodtrabajadorActionPerformed

    private void jTfechaeventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfechaeventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfechaeventoActionPerformed

    private void jBconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conexion=DriverManager.getConnection("jdbc:mysql://localhost/eventos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDateTimeCode=false&serverTimezone=UTC","root","");
            Statement s=conexion.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM ocurrencia");
            jClistaeventos.removeAllItems();
            jClistaeventos.addItem("Evento");
            int cevento, cfalla, ctrabajador;
            String fevento, freparacion, estatus; 
            while (rs.next()){
                cevento=rs.getInt(1);
                cfalla=rs.getInt(2);
                fevento=String.valueOf(rs.getDate(3));
                freparacion=String.valueOf(rs.getDate(4));
                ctrabajador=rs.getInt(5);
                estatus=rs.getString(6);
                Ocurrencia ob=new Ocurrencia(cevento,cfalla,fevento,freparacion,ctrabajador,estatus);
                lo.add(ob);
                jClistaeventos.addItem(String.valueOf(cevento));
            }
        } 
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TablaOcurrencia.class.getName()).log(Level.SEVERE, null, ex);
        }
                

        
    }//GEN-LAST:event_jBconsultarActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        int eventoseleccionado;
        eventoseleccionado=jClistaeventos.getSelectedIndex();
        if (eventoseleccionado!=0){
            String buscarevento=(String) jClistaeventos.getSelectedItem();
            for (Ocurrencia ob:lo){
                if (buscarevento.equals(String.valueOf(ob.getCodOcurrencia()))){
                    jTcodfalla.setText(String.valueOf(ob.getCodFalla()));
                    jTcodtrabajador.setText(String.valueOf(ob.getCodTrabajador()));
                    jTfechaevento.setText(ob.getFechaOcurrencia());
                    jTfechareparacion.setText(ob.getFechaReparacion());
                    jTestatusactual.setText(ob.getEstatus());
                }
            }
        }
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        // TODO add your handling code here:
        int eventoseleccionado;
        eventoseleccionado=jClistaeventos.getSelectedIndex();
        if (eventoseleccionado!=0){
            String eliminarevento=(String) jClistaeventos.getSelectedItem();
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conexion=DriverManager.getConnection("jdbc:mysql://localhost/eventos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDateTimeCode=false&serverTimezone=UTC","root","");
                String sql="DELETE FROM ocurrencia WHERE cod_evento=?";
                PreparedStatement ps=null;
                ps=conexion.prepareStatement(sql);
                ps.setInt(1,Integer.parseInt(eliminarevento));
                ps.executeUpdate();
                /*
                for (Ocurrencia ob:lo){
                    if(ob.getCodOcurrencia()==Integer.parseInt(eliminarevento)){
                        lo.remove(ob);
                    }
                }
                */
            }   
            catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(TablaOcurrencia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaOcurrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaOcurrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaOcurrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaOcurrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaOcurrencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBcambioestatus;
    private javax.swing.JButton jBconsultar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBvolver;
    private javax.swing.JComboBox<String> jCelementosestatus;
    private javax.swing.JComboBox<String> jClistaeventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLevento;
    private javax.swing.JLabel jLfalla;
    private javax.swing.JLabel jLfechaevento;
    private javax.swing.JLabel jLfechareparacion;
    private javax.swing.JLabel jLlistaestatus;
    private javax.swing.JLabel jLnombrefalla;
    private javax.swing.JLabel jLnombretrabajador;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JLabel jLtrabajador;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTcodfalla;
    private javax.swing.JTextField jTcodtrabajador;
    private javax.swing.JTextField jTestatusactual;
    private javax.swing.JTextField jTfechaevento;
    private javax.swing.JTextField jTfechareparacion;
    // End of variables declaration//GEN-END:variables
}
